### ISSUE TITLE
Use pandoc filter for converting?

### ISSUE THREAD

**Issue by kentookura** [Conair94/ModelTheoryWiki#1]
I am creating this issue beacause I couldn't find a contact email.
I am working on a pandoc filter for forester. It shouldn't require a lot of work to make the output of the filter satisfactory, so you could use pandoc to convert the wiki. Are you interested in this?

**Comment by Conair94** [comment]
I just added a contact email. In the future you can email me at connorl@umd.edu or use create an issue like so. 
I do not know what pandoc is but if it is helpful sure. I should disclaim that my programming knowledge is the bare minimum required to set up this GitHub page so I am not sure how much help I will be. Of course, I am interested in improving the wiki so if this would be helpful then yes I am interested.
